server:
  port: 8009
  servlet:
    context-path: /app
    session:
      timeout: 300s
spring:
  datasource:
    password: npg_BCb5pDLgK7Gf
    url: jdbc:postgresql://ep-dark-mountain-adrpuebo-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
          import_files: scripts/0_user.sql
settings:
  auth:
    token-time: 60
  puntored:
    base-url: https://us-central1-puntored-dev.cloudfunctions.net/technicalTest-developer/api
    api-key: mtrQF6Q11eosqyQnkMY0JGFbGqcxVg5icvfVnX1ifIyWDvwGApJ8WUM8nHVrdSkN
    user: user0147
    password: '#3Q34Sh0NlDS'
  cors:
    allowed-origins: https://tx-portal-front.vercel.app

